# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: 'publish @lokmeinmatz/my-ui'

on:
  release:
    types: [created]

jobs:
  build:
    uses: ./.github/workflows/build.yaml

  publish-ui-gpr:
    needs: build
    runs-on: ubuntu-latest
    defaults:
     run:
      working-directory: ./packages/ui
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - name: Donwload build artifact
        uses: actions/download-artifact@v3
        with:
          name: packages-ui-dist
      - uses: actions/setup-node@v3
        with:
          always-auth: true
          node-version: 18
          registry-url: https://npm.pkg.github.com/
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7
          run_install: false
      - name: Publish normal
        working-directory: ./packages/ui
        run: pnpm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
